name: Turborepo CI

on:
  push:
    branches: ['main']
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./turbo

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Debug - List directory contents
        run: ls -l turbo

      - name: Setup Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Turborepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.TURBO_TOKEN }}

      - name: Build
        run: yarn build --api="http://127.0.0.1:9080" --token="${{ secrets.TURBO_TOKEN }}" --team="${{ vars.TURBO_TEAM }}"
