name: Turborepo CI

on:
  push:
    branches: ['main']
    paths:
      - './turbo'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    environment: stage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./turbo

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('.turbo/**') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: ./turbo/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      # - name: Turborepo local server
      #   uses: felixmosh/turborepo-gh-artifacts@v2
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     server-token: ${{ secrets.TURBO_TOKEN }}
      - name: Build
        run: pnpm turbo run build --filter=web...
        # env:
        #   TURBO_API: 'http://127.0.0.1:9080'
        #   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        #   TURBO_TEAM: ${{ vars.TURBO_TEAM }}
