name: Turborepo CI

on:
  push:
    branches: ['main']
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./turbo

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Debug - List directory contents
        run: ls -l

      - name: Setup Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: ./turbo/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Log secrets and vars
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Using secret token: $TURBO_TOKEN"
          echo "Using vars token: $TURBO_TEAM"
          echo "Using github token: $GITHUB_TOKEN"

      - name: Turborepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.TURBO_TOKEN }}

      - name: Build
        run: pnpm --filter=web... run build --api="http://127.0.0.1:9080" --token="${{ secrets.TURBO_TOKEN }}" --team="${{ vars.TURBO_TEAM }}"
