name: Turborepo CI for Vercel

on:
  push:
    branches: ['main']
    paths:
      - 'turbo/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    environment: stage
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.VERCEL_TURBO_TEAM }}
    defaults:
      run:
        working-directory: ./turbo

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: ./turbo/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm turbo run build --filter=web...
